apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-config
data:
  # This is where we'd store test plan specifics or configuration overrides
  test-config.properties: |
    # Target service using K8s DNS
    target_host=api-gateway-service.default.svc.cluster.local
    target_port=5000
    threads=10
    rampup=30
    duration=300
    
  # You can add additional test plans or properties files here
  run-test.sh: |
    #!/bin/bash
    TEST_PLAN=${TEST_PLAN:-"jmeterConfigurationFile.jmx"}
    TEST_DIR=/jmeter/scripts
    RESULTS_DIR=/jmeter/results
    
    echo "Running JMeter test plan: ${TEST_PLAN}"
    jmeter -n -t ${TEST_DIR}/${TEST_PLAN} \
      -l ${RESULTS_DIR}/results.jtl \
      -j ${RESULTS_DIR}/jmeter.log \
      -e -o ${RESULTS_DIR}/dashboard