FROM public.ecr.aws/docker/library/python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app2.py .
COPY gunicorn_config.py .
ENV FLASK_APP=app2.py
EXPOSE 5000
CMD ["gunicorn", "--config", "gunicorn_config.py", "app2:app"]

