FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY gateway.py .
COPY gunicorn_config.py .
ENV FLASK_APP=gateway.py
EXPOSE 5000
CMD ["gunicorn", "--config", "gunicorn_config.py", "gateway:app"]
