FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app1.py .
COPY gunicorn_config.py .
COPY Training/ ./Training/
ENV FLASK_APP=app1.py
EXPOSE 5000
CMD ["gunicorn", "--config", "gunicorn_config.py", "app1:app"]
