FROM public.ecr.aws/docker/library/python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app2.py .
ENV FLASK_APP=app2.py
EXPOSE 5000
CMD ["python", "app2.py"]
