apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1
  template:
    metadata:
      labels:
        app: flask-app-1
    spec:
      containers:
      - name: flask-app-1
        image: localhost:5000/flask-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-1-service
spec:
  selector:
    app: flask-app-1
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-2
  template:
    metadata:
      labels:
        app: flask-app-2
    spec:
      containers:
      - name: flask-app-2
        image: localhost:5000/flask-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-2-service
spec:
  selector:
    app: flask-app-2
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort