apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        monitoring: 'true'
    spec:
      containers:
      - image: flask-app-gateway:latest
        imagePullPolicy: Never
        name: api-gateway
        # resources:
        #   limits:
          #   memory: "1Gi"
            # cpu: "1000m"
          # requests:
            # memory: "1Gi"
            # cpu: "1000m"
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8000
          name: metrics
      serviceAccountName: flask-app-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 8000
    targetPort: 8000
  selector:
    app: api-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1
  template:
    metadata:
      labels:
        app: flask-app-1
        monitoring: 'true'
    spec:
      containers:
      - image: flask-app1:latest
        imagePullPolicy: Never
        name: flask-app-1
        resources:
          limits:
            # memory: "1Gi"
            cpu: "1000m"
          requests:
            # memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-1-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app-1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-2
  template:
    metadata:
      labels:
        app: flask-app-2
        monitoring: 'true'
    spec:
      containers:
      - image: flask-app2:latest
        imagePullPolicy: Never
        name: flask-app-2
        resources:
          limits:
            # memory: "1Gi"
            cpu: "1000m"
          requests:
            # memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-2-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app-2
  type: NodePort
