apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1
  template:
    metadata:
      labels:
        app: flask-app-1
        monitoring: "true"
    spec:
      containers:
      - name: flask-app-1
        image: localhost:5000/flask-app1:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-1-service
spec:
  selector:
    app: flask-app-1
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-2
  template:
    metadata:
      labels:
        app: flask-app-2
        monitoring: "true"
    spec:
      containers:
      - name: flask-app-2
        image: localhost:5000/flask-app2:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-2-service
spec:
  selector:
    app: flask-app-2
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        monitoring: "true"
    spec:
      containers:
      - name: api-gateway
        image: localhost:5000/flask-app-gateway:latest
        ports:
        - containerPort: 5050
          name: http
        - containerPort: 8000
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 5050
    targetPort: 5050
  - name: metrics
    port: 8000
    targetPort: 8000
  type: NodePort