adminUser: admin
adminPassword: admin123

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30091

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ""
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: "matrix-operations-dashboard"
